server:
  port: 8082
  host: localhost
auth:
  jwksUri: http://localhost:8080/.well-known/jwks.json
database:
  url: mongodb://root:root@localhost:27017/order_db?authSource=admin&w=1
frontend:
  clientUI: http://localhost:3000
  adminUI: http://localhost:5173

kafka:
  broker: localhost:9092
